os: linux

language: python

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

env:
  - DJANGO="Django<2.3"     # Django 2.2.x LTS
  - DJANGO="Django<3.1"     # Django 3.0.x

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  exclude:
    # Django 3.0 doesn't support Python 3.5
    - env: DJANGO="Django<3.1"
      python: 3.4
    - env: DJANGO="Django<3.1"
      python: 3.5

# Command to install dependencies
install:
  # Latest PIP uses wheel by default
  - pip install --upgrade pip
  - pip install $DJANGO
  - pip install coveralls

# Command to run tests
script: coverage run setup.py test

after_success:
  coveralls
