language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO=Django==1.4.10
  - DJANGO=Django==1.5.5
  - DJANGO=Django==1.6.2
  - DJANGO=https://www.djangoproject.com/m/releases/1.7/Django-1.7a1.tar.gz

matrix:
  allow_failures:
    # Allow failures for unreleased Django version
    - env: DJANGO=https://www.djangoproject.com/m/releases/1.7/Django-1.7a1.tar.gz

# command to install dependencies
install:
  - pip install -q $DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors

# command to run tests
script: python setup.py test
