language: python

python:
# Disable 2.5 for now due to a bug in django-setuptest
# Ref: https://github.com/praekelt/django-setuptest/pull/6
#  - "2.5" 
  - "2.6"
  - "2.7"

env:
  - DJANGO=Django==1.3.4
  - DJANGO=Django==1.4.2
  - DJANGO=https://www.djangoproject.com/download/1.5a1/tarball/

# command to install dependencies
install:
  - pip install -q $DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors

# command to run tests
script: python setup.py test
