language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO=Django==1.4.5
  - DJANGO=Django==1.5.1
  - DJANGO=Django==1.6b1

matrix:
  allow_failures:
    # Allow failures for unreleased Django version
    - env: DJANGO=Django==1.6b1

# command to install dependencies
install:
  - pip install -q $DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors

# command to run tests
script: python setup.py test
