language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO=Django==1.4.6
  - DJANGO=Django==1.5.2
  - DJANGO=https://www.djangoproject.com/m/releases/1.6/Django-1.6b2.tar.gz

matrix:
  allow_failures:
    # Allow failures for unreleased Django version
    - env: DJANGO=https://www.djangoproject.com/m/releases/1.6/Django-1.6b2.tar.gz

# command to install dependencies
install:
  - pip install -q $DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors

# command to run tests
script: python setup.py test
