os: linux

language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8

env:
  - DJANGO="Django<1.12"    # Django 1.11.x LTS
  - DJANGO="Django<2.3"     # Django 2.2.x LTS
  - DJANGO="Django<3.1"     # Django 3.0.x

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  exclude:
    # Django 1.11 doesn't support Python 3.8
    - env: DJANGO="Django<1.12"
      python: 3.8

    # Django 2.2 doesn't support Python 2.7 and 3.4
    - env: DJANGO="Django<2.3"
      python: 2.7
    - env: DJANGO="Django<2.3"
      python: 3.4

    # Django 3.0 doesn't support Python 2.7, 3.4 and 3.5
    - env: DJANGO="Django<3.1"
      python: 2.7
    - env: DJANGO="Django<3.1"
      python: 3.4
    - env: DJANGO="Django<3.1"
      python: 3.5

# Command to install dependencies
install:
  # Latest PIP uses wheel by default
  - pip install --upgrade pip
  - pip install $DJANGO
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install coveralls

# Command to run tests
script: coverage run setup.py test

after_success:
  coveralls
