name: Test

on: [push, pull_request]

jobs:
  build:
    name: build (Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
        django-version: ['4.2', '5.1', '5.2', 'main']
        exclude:
          # No such tox envs:
          - { python-version: '3.12', django-version: '4.2' }
          - { python-version: '3.13', django-version: '4.2' }
          - { python-version: '3.9', django-version: '5.1' }
          - { python-version: '3.9', django-version: '5.2' }
          - { python-version: '3.9', django-version: 'main' }
          - { python-version: '3.10', django-version: 'main' }
          - { python-version: '3.11', django-version: 'main' }

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    - name: Cache and install system deps for python-ldap
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libldap2-dev libsasl2-dev libssl-dev
        version: 1.0

    - name: Ensure system deps installed
      run: sudo apt-get install -y libldap2-dev libsasl2-dev libssl-dev

    - name: Tox tests
      run: uvx --python ${{ matrix.python-version }} --with tox-uv --with tox-gh-actions tox
      env:
        DJANGO: ${{ matrix.django-version }}

    - name: Upload coverage
      uses: codecov/codecov-action@v4
      with:
        name: Python ${{ matrix.python-version }}
